site_name: Streckenkunde Digital
copyright: © 2024 | Dennis Heinrich
repo_url: https://github.com/Streckenkunde/Anwenderdokumentation
theme:
  language: de
  name: material
  palette:
    primary: black
    accent: teal
  features:
    - toc.follow
    - navigation.footer

plugins: 
  - search
  - mkpdfs

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cloudmaker97

nav:
  - Startseite: index.md
  - Allgemeines:
    - 1_general/1_about.md
    - 1_general/2_changes.md
    - 1_general/3_development.md
  - Funktionen und Module:
    - 2_modules/1_welcome/index.md
    - 2_modules/2_dashboard/index.md
    - Dokumentation:
      - 2_modules/3_documentation/index.md
      - 2_modules/3_documentation/1_routes/index.md
      - 2_modules/3_documentation/2_tours/index.md
    - Mein Konto:
      - 2_modules/4_account/index.md
  - Weitere Informationen:
    - 3_extras/1_app/index.md