name: Dokumentation ändern
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Git Credentials setzen
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Cache-ID anzeigen
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - name: Cache nutzen
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: MkDocs installieren
        run: pip install mkdocs-material 
      - name: GitHub Pages veröffentlichen
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: help.streckenkunde.dennis-heinri.ch
