name: Dokumentation ändern
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Projekt herunterladen
        uses: actions/checkout@v2

      - name: Dokumentation hochladen
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: help.streckenkunde.dennis-heinri.ch
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: requirements.txt